### PR TITLE
test: workaround IE11 defficiencies

### LINKED ISSUE #471: IE11 fails in CI
https://travis-ci.org/snabbdom/snabbdom/builds/611279225#L362-L414

### PR DESCRIPTION
**Pull request by mightyiam**
Fixes #471.

### CODE REVIEW

File: src/test/attributes.ts [hunk 1]
```diff
@@ -38,10 +38,10 @@ describe('attributes', function () {
...
     var vnode1 = h('div', { attrs: { href: null as any, minlength: 0, value: '', title: 'undefined' } });
     elm = patch(vnode0, vnode1).elm;
-    assert.strictEqual(elm.getAttribute('href'), 'null');
-    assert.strictEqual(elm.getAttribute('minlength'), '0');
-    assert.strictEqual(elm.getAttribute('value'), '');
-    assert.strictEqual(elm.getAttribute('title'), 'undefined');
+    assert.ok(elm.hasAttribute('href'));
+    assert.ok(elm.hasAttribute('minlength'));
+    assert.ok(elm.hasAttribute('value'));
+    assert.ok(elm.hasAttribute('title'));
```
Comment (mightyiam) [inline src/test/attributes.ts]: In IE11, the value for attributes set to `null` ends up being an actual `null`, instead of a `'null'` string. So I figured it would be best to just test for the existence of these attributes, instead of their values. "are not omitted" seems to be covered. I feel this is good enough.

File: src/test/attributes.ts [hunk 2]
```diff
@@ -77,11 +77,11 @@ describe('attributes', function () {
...
       assert.strictEqual(elm.getAttribute('required'), null);
     });
-    it('is not omitted if the value is falsy but casted to string', function () {
+    it('is not omitted if the value is falsy', function () {
       var vnode1 = h('div', { attrs: { readonly: 0, noresize: null as any } });
       elm = patch(vnode0, vnode1).elm;
-      assert.strictEqual(elm.getAttribute('readonly'), '0');
-      assert.strictEqual(elm.getAttribute('noresize'), 'null');
+      assert.ok(elm.hasAttribute('readonly'));
+      assert.ok(elm.hasAttribute('noresize'));
```
Comment (mightyiam) [inline src/test/attributes.ts]: Casting to a string is most likely performed by the platform. And since IE11 seems to keep the `null` as a real `null`, it seems enough for us to test for the presence of the boolean attribute. A boolean attribute with `null` as a value is still present (truthy), right?

File: src/test/core.ts [hunk 3]
```diff
@@ -11,6 +11,8 @@ import vnode, { VNode } from '../vnode'
 import htmlDomApi from '../htmldomapi'
 import { CreateHook, InsertHook, PrePatchHook, RemoveHook, InitHook, DestroyHook, UpdateHook } from '../hooks'
 
+const hasSvgClassList = 'classList' in SVGElement.prototype
```
Comment (mightyiam) [inline src/test/core.ts]: IE11 does not have a `classList` on `SVGElement`. So some tests would just be skipped in it. I'm OK with that.

File: src/test/core.ts [hunk 4]
```diff
@@ -322,7 +326,7 @@ describe('snabbdom', function () {
         var prevElm = document.createElement('div');
         prevElm.id = 'id';
         prevElm.className = 'class';
-        var text = new Text('Foobar');
+        var text = document.createTextNode('Foobar');
```
Comment (mightyiam) [inline src/test/core.ts]: IE11 does not have `window.Text`.

File: src/test/core.ts [hunk 5]
```diff
@@ -358,9 +362,10 @@ describe('snabbdom', function () {
         assert.strictEqual(elm.childNodes[0].textContent, 'Hello');
       });
       it('can work with domApi', function () {
-        var domApi = Object.assign({}, htmlDomApi, {
+        var domApi = {
+          ...htmlDomApi,
           tagName: function (elm: HTMLElement) { return 'x-' + elm.tagName.toUpperCase(); }
-        });
+        };
```
Comment (mightyiam) [inline src/test/core.ts]: IE11 does not have `Object.assign`.

File: src/test/style.ts [hunk 6]
```diff
@@ -9,6 +9,10 @@ var patch = init([
   styleModule
 ]);
 
+const featureDiscoveryElm = document.createElement('div')
+featureDiscoveryElm.style.setProperty('--foo', 'foo')
+const hasCssVariables = featureDiscoveryElm.style.getPropertyValue('--foo') === 'foo'
```
Comment (mightyiam) [inline src/test/style.ts]: IE11 does not have CSS variables. Simply skip those tests in it. I'm OK with that.

**Comment by mightyiam** [comment]
Take a look at this line in CI where IE11 passes :fireworks: 
https://travis-ci.org/snabbdom/snabbdom/builds/638732294#L320

File: src/test/attributes.ts (hunk 1 above)
Comment (kuraga) [reply src/test/attributes.ts]: So `elm.getAttribute('href')` is `null` instead of `'null'` in IE11. What about three else lines?

File: src/test/attributes.ts (hunk 2 above)
Comment (kuraga) [reply src/test/attributes.ts]: So `elm.getAttribute('noresize')` is `null` instead of `'null'` in IE11. What about the first line?

File: src/test/core.ts [hunk 7]
```diff
@@ -145,6 +147,7 @@ describe('snabbdom', function () {
       assert(!elm.classList.contains('not'));
     });
     it('receives classes in selector when namespaced', function () {
+      if (!hasSvgClassList) return
```
Comment (kuraga) [inline src/test/core.ts]: Why `return` not `skip`?

**Comment by kuraga** [comment]
@mightyiam thanks! Add `IE11 workaround` comment everywhere?

File: src/test/attributes.ts (hunk 1 above)
Comment (mightyiam) [reply src/test/attributes.ts]: Just keeping it consistent and loyal to the purpose of this specific test. "Not omitted".

File: src/test/attributes.ts (hunk 2 above)
Comment (mightyiam) [reply src/test/attributes.ts]: `hasAttribute` is all that's necessary for a boolean attribute, I figure.

File: src/test/core.ts (hunk 7 above)
Comment (mightyiam) [reply src/test/core.ts]: What API includes, `skip`, please? Is that a mocha thing?

**Comment by mightyiam** [comment]
@kuraga, I prefer to refrain from name-calling in test skipping. Feature detection seems to be a better idea anyway. Whatever browser doesn't have CSS variables, for example. I don't care what browser that is.

**Comment by kuraga** [comment]
@mightyiam I meant to highlight a trick. To remove it (trick) when we would decide to drop IE11 support.

File: src/test/core.ts (hunk 7 above)
Comment (kuraga) [reply src/test/core.ts]: https://mochajs.org/#inclusive-tests, `this.skip(...)`

**Comment by mightyiam** [comment]
I don't know what are our supported browsers. It could be that it's not only IE11 that lacks CSS variables, for example. The, what would the comment say? It doesn't seem important enough to figure this all out, to me. If it ever bothers anyone, they could check whether it still passes CI and that would be it. Or if you'd like to come up with the correct comments then I'd support that.

**Comment by kuraga** [comment]
@mightyiam ,

> It could be that it's not only IE11

there is a probability there will be much code for _only_ one browser. And we drop support of this browser it would be nice to remove code tricks for it (to make code simpler). Comments could help to find out this code.

But I see your position, question seems to be settled.

File: src/test/core.ts (hunk 7 above)
Comment (mightyiam) [reply src/test/core.ts]: Good tip. Done.

File: src/test/core.ts (hunk 3 above)
Comment (jvanbruegge) [reply src/test/core.ts]: you can also load a classlist polyfill for this case

Comment (mightyiam) [reply src/test/core.ts]: Thanks, @jvanbruegge. I actually did that and then changed to this. Have a feeling that this is better. Not sure why.
