### PR TITLE
fix(dataset): check if property exist before deleting

### LINKED ISSUE #309: deleting a dataset property that doesn't exist throws an error
Found out that Safari automatically deletes the dataset property when you do `use strict;`

So when [this line of code](
https://github.com/snabbdom/snabbdom/blob/7b45afea49a32e2f4b0c5f12ca7df0040fd1dcf7/src/modules/dataset.ts#L23) run, it may error. So maybe an extra checking? `if (d && d[key]) {`

I have a PR ready

### PR DESCRIPTION
**Pull request by FeliciousX**
in Safari, when it is `use strict`, if the dataset property is removed in DOM
deleting it again will cause an error

closes #309

### CODE REVIEW

File: src/modules/dataset.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ function updateDataset(oldVnode: VNode, vnode: VNode): void {
 
   for (key in oldDataset) {
     if (!dataset[key]) {
-      if (d) {
+      if (d && d[key]) {
```
Comment (caridy) [inline src/modules/dataset.ts]: this is not enough. this will fail if `elm.dataset.x = 0` or any other falsy value. you will have to change this to `if (d && key in d) {` to only delete it if the key exists.

Comment (caridy) [inline src/modules/dataset.ts]: ... but if you look at the other code path with the `removeAttribute`, we don't want to invoke that one if dataset is available (which is for HTMLElement but not for Element). So, I guess you just need to protect the delete invocation only. something like:

```
if (d) {
   if (key in d) {
       delete d[key];
   }
} else {
   ...
}
```

**Comment by FeliciousX** [comment]
done :D @caridy

**Comment by paldepind** [comment]
Great! Thank you 😄
